//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v3.0-03/04/2009 09:20 AM(valikov)-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.09.14 at 01:51:37 PM MESZ 
//

import org.jvnet.jaxb2_commons.xml.bind.ContextPathAware;

public class RoundtripTest
    extends org.jvnet.hyperjaxb3.ejb.test.RoundtripTest
    implements ContextPathAware
{


    public String getContextPath() {
        return "de.thorstenberger.taskmodel.complex.complextaskdef";
    }

}
